name: PRINTING WORKFLOW

on:
  push:
  pull_request:
  release:
  create:
    tags:
      - '*'
  issues:
  issue_comment:
  pull_request_review:
  pull_request_review_comment:
  milestone:
  label:
  repository_dispatch:

jobs:
  print-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Print actions github builtin variables
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_CONTEXT"

      - name: watch
        run: echo ${{ github.repository_owner }}
